REPORT_DELETE_PDF_EXISTS = "REPORT_DELETE_PDF_EXISTS"
REPORT_DELETE_LOCKED = "REPORT_DELETE_LOCKED"
REPORT_DELETE_PUBLISHED_ISSUES = "REPORT_DELETE_PUBLISHED_ISSUES"
REPORT_DELETE_PROCESSING_COMPLETE = "REPORT_DELETE_PROCESSING_COMPLETE"
FIELD_VISIT_REPORT_NOT_FOUND = "FIELD_VISIT_REPORT_NOT_FOUND"
WEEKLY_REPORT_NOT_FOUND = "WEEKLY_REPORT_NOT_FOUND"

REPORT_DELETE_REASON_HE: dict[str, str] = {
    REPORT_DELETE_PDF_EXISTS: "לא ניתן למחוק דוח לאחר שהופק ונשמר PDF",
    REPORT_DELETE_LOCKED: "לא ניתן למחוק דוח שנשלח או ננעל",
    REPORT_DELETE_PUBLISHED_ISSUES: (
        "לא ניתן למחוק דוח שקשורים אליו ליקויים שפורסמו"
    ),
    REPORT_DELETE_PROCESSING_COMPLETE: "לא ניתן למחוק דוח שעבר עיבוד במערכת",
}

LOCKED_FIELD_VISIT_STATUSES = frozenset({"LOCKED", "PENDING_UPLOAD"})
